// <auto-generated />
using Dojo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dojo.Migrations
{
    [DbContext(typeof(DojoContext))]
    [Migration("20220803164940_CorrectSpellingForSenseiId")]
    partial class CorrectSpellingForSenseiId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Dojo.Models.Disciple", b =>
                {
                    b.Property<int>("DiscipleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DiscipleId");

                    b.ToTable("Disciples");
                });

            modelBuilder.Entity("Dojo.Models.DiscipleSensei", b =>
                {
                    b.Property<int>("DiscipleSenseiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DiscipleId")
                        .HasColumnType("int");

                    b.Property<int>("SenseiId")
                        .HasColumnType("int");

                    b.HasKey("DiscipleSenseiId");

                    b.HasIndex("DiscipleId");

                    b.HasIndex("SenseiId");

                    b.ToTable("DiscipleSensei");
                });

            modelBuilder.Entity("Dojo.Models.MartialArt", b =>
                {
                    b.Property<int>("MartialArtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("MartialArtId");

                    b.ToTable("MartialArts");
                });

            modelBuilder.Entity("Dojo.Models.Sensei", b =>
                {
                    b.Property<int>("SenseiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MartialArtId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SenseiId");

                    b.ToTable("Senseis");
                });

            modelBuilder.Entity("Dojo.Models.DiscipleSensei", b =>
                {
                    b.HasOne("Dojo.Models.Disciple", "Disciple")
                        .WithMany("JoinEntities")
                        .HasForeignKey("DiscipleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dojo.Models.Sensei", "Sensei")
                        .WithMany("JoinEntities")
                        .HasForeignKey("SenseiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disciple");

                    b.Navigation("Sensei");
                });

            modelBuilder.Entity("Dojo.Models.Disciple", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("Dojo.Models.Sensei", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
